cart/urls.py
from django.urls import path
from .import views

app_name='cart'


urlpatterns = [
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove')
    
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('payment/', include('payment.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views

app_name='order'

urlpatterns = [
    path('', views.order_create, name='order_create'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from secrets import choice
from django import forms
from pkg_resources import require

PRODUCT_QUANTITY_FORM = [(i, str(i)) for i in range(1,11)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(coerce=int, 
                                      choices = PRODUCT_QUANTITY_FORM)
    
    override = forms.BooleanField(required=False,
                                           initial=False,
                                           widget=forms.HiddenInput)
    
    
    

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from.cart import Cart
from shop.models import Product
from.forms import CartAddProductForm

# Create your views here.

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                quantity =cd['quantity'],
                override_quantity= cd['override'])
        
    return redirect('cart:cart_detail')
            
            
@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity':item['quantity'],
            'override': True
        })
    return render(request, 'cart/cart_detail.html', {'cart':cart})

templates/cart/cart_detail.html
{% extends 'home/index.html' %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cart</title>
</head>
<body>

    <!-- creating item cart -->
    
    {% block content %}

    {% for item in cart %}
    {% with product=item.product %}
        
    <img src="{{ product.image.url }}" alt="" width="150px">

    <p>Quantity: {{ item.quantity }}</p>
    <form action="{% url 'cart:cart_remove' product.id %}" method="post">
        {% csrf_token %}
        <button type="submit">remove</button>
        
    </form>

    <form action="{% url 'cart:cart_add' product.id %}" method="post">
        {% csrf_token %}
        {{ item.update_quantity_form.quantity}}
        {{ item.update_quantity_form.override }}
        <button type="submit">update</button>
    </form>
    {% endwith %}

              
    {% endfor %}

    <form action="{% url 'order:order_create' %}" method="post">
        {% csrf_token %}
        <button type="submit">checkout</button>
    </form>

    <a href="{% url 'shop:product_list' %}"> continue shopping</a>
        
        
    {% endblock content %}     

    
    
    
</body>
</html>